no_display=1
toggle_hud=Shift_R+F12
position=top-right

preset=1

fps_metrics=avg,0.01
fps_sampling_period=500
frame_timing

gpu_stats
gpu_temp
gpu_power
vram
gpu_list=0

cpu_stats
cpu_temp
ram

font_size=20
background_alpha=0.35
round_corners=8
text_outline
